# Generated by Django 4.1.1 on 2023-04-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_userfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userfile',
            old_name='fd',
            new_name='user',
        ),
    ]
