# Generated by Django 4.1.1 on 2023-04-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_alter_userfile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
