# Generated by Django 4.1.1 on 2023-04-14 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0006_alter_userfile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='key',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
